
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./envs/.postgres.env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  rmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  db:
    driver: local